### PR TITLE
Vim casting

### PR DESCRIPTION
**Pull request by nyancol**
This pull request introduces new clever algorithm to cast the colors of the generated palette to vim's syntactic groups, it features:
- Clustering to classify the colors into according to the number of major syntactic groups
- Quadratic assignment to maximize the distance between the colors of two frequent syntactic groups.

I advice you to review the three previous pull request before starting this one.

The clustering algorithm could be useful for other purposes, such as terminal color casting (or lightline, yabar ...). For instance, the colors could be first classified into K clusters, K standing for the number of colors that can be affected to a terminal profile, and then use the medoids of each cluster as the color.

### CODE REVIEW

**Review by romzie — APPROVED** [review]
One color is selected for each major group or each minor group?
If major, it would be good to have subgroups of different color, what do you think?

**Comment by nyancol** [comment]
One cluster of colors is selected for each major syntactic group (e.g., `Statement` is a major syntactic group, that contains: `Conditional`, `Repeat` etc.), and then colors from the cluster are mapped to the subgroups of the group. My idea was that `if` and `for` should have similar hues. But know that I think of it, that might not be true for `Constant`, which includes `String`, `Character`, `Number`, etc.
Any thoughts?

**Comment by nyancol** [comment]
Here's the list:
Vim syntaxV

**Comment by romzie** [comment]
Yes I was mostly thinking about the Constant group, and the difference between string and numbers and booleans

**Comment by nyancol** [comment]
Do splitting the `Constant` group into: `[[String, Character], [Constant, Number, Float], [Boolean]]` would be enough to overcome this issue?

**Pull request closed without merging**
